### ISSUE TITLE
Ways for improvement

### ISSUE THREAD

**Issue by Lolf1010** [radoslawkalamon/prime-numbers-from-arrays#2]
I found your project, looked into the code and i think found some ways to improve the code and therefore the efficiency:

### isArrayWithNumbers:
- l.12/18: instead of `if (x === false) ...` you could use `if (!x) ...`
- l.17: instead of using `.some(isNaN)`, which does not catch `Infinity` (results in endless loop in primality-test), you could use [.every(Number.isInteger)](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger) which works perfectly

### isPrimeNumber:
- i think you know that this function can be improved
- the efficiency can simply but heavily be improved
  - use only odd numbers
  - use only numbers up to sqrt(n)
  - (there are a lot more ways to reduce the runtime)

```javascript
export default (_element) => {
  const element = Math.abs(_element);
  if (element % 2 === 0) { return false; }
  for (let i = 3, j = Math.round(Math.sqrt(element)); i <= j; i += 2) {
    if (element % i === 0) {
      return false;
    }
  }
  return true;
};
```

- Efficiency for `prime(999999937)`
  - before: `5010.94ms`
  - after: `0.60ms`

Hope i can help.

**Comment by radoslawkalamon** [comment]
Hi @Lolf1010,

Good point with _Infinity_ in **isArrayWithNumbers**. I implemented your comments in it and created unit tests.

Yep, **isPrimeNumber** should get more love before. Your code is great and way more efficient! Can you create Pull Request for it?

Thanks for your comments!

**Comment by Lolf1010** [comment]
@radoslawkuswik I took a deeper look into the other functions of the code.

- Prime numbers are positive numbers: `Math.abs()` should be removed?
- empty arrays must not be dropped, they will anyways during `reduce`
- currently an array is dropped completely if a single value is invalid. Would it be better to just drop the invalid numbers and keep the rest, like this:
  - Array of elements --> Array of arrays of elements --> Array of unique elements -->  Array of unique primes --> Array of unique primes in ascending order

```javascript
// Function to check if number is prime
function isPrime(n) {
  if (!Number.isInteger(n)) return false;
  if (n < 4) return n > 1;
  if (n % 2 === 0 || n % 3 === 0) return false;

  for (let i = 5, j = Math.round(Math.sqrt(n)); i <= j; i += 4) {
    if (n % i === 0) return false;
    i += 2;
    if (n % i === 0) return false;
  }

  return true;
};

// Complete function
args.filter(Array.isArray)                            // Only arrays
    .reduce((x, y) => [...new Set([...x, ...y])], []) // Only unique elements
    .filter(prime)                                    // Only numbers which are prime
    .sort((x, y) => x - y)                            // Ascending order

// Test
[[],['c'],["b",undefined,2,NaN],[Infinity,-0,7,-2],[3,1,5],'a',"a",11,undefined]
// [2, 3, 5, 7]
```

The way you divide the projects into its parts by using separate files is great but may be a little too much for a project of this size.

**Comment by radoslawkalamon** [comment]
@Lolf1010:
- Seven month ago, I found this article [https://primes.utm.edu/notes/faq/negative_primes.html](https://primes.utm.edu/notes/faq/negative_primes.html). but today, after consideration, I think that `Math.abs()` should be removed. Please link to Wikipedia - [https://en.wikipedia.org/wiki/Prime_number](https://en.wikipedia.org/wiki/Prime_number) - in description of isPrimeNumber function for the Prime Number definition.
- I agree with this, but...
- ...disagree with this one. Getting prime numbers from arrays with mixed content will be breaking change for `v2.x.x`, so we should leave it as it is for now. Users should only pass arrays of numbers to the function and filter input on their behalf. I think that for `v3.x.x`, script should throw error for non-numbers array and there should be an option to explicitly turn it off - something like `getPrimeNumbers(true, [...x], [...y])`. With this turned off, script could get Prime Numbers from any array passed.
- I agree with the argument for using separate files for project, but the script was created with this in mind, so I will leave it as it is.

**Comment by Lolf1010** [comment]
Ok.
I did the changes we discussed and some minor changes to increase readability.
I did not change the .min.js-file or change the README - you may want to add that ;)
